version: "3"
services:
  possbot:
    container_name: possbot
    image: http://ghcr.io/emmathepossum/possbot
    volumes:
      - "./images:/home/bun/app/images"
    restart: always
    env_file: .env
